# Generated by Django 3.0.5 on 2020-05-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(auto_now=True)),
                ('pub_time', models.DateTimeField(auto_now=True)),
                ('pressure_avg', models.FloatField()),
                ('pressure_min', models.FloatField()),
                ('pressure_max', models.FloatField()),
                ('wind_speed_avg', models.FloatField()),
                ('wind_speed_min', models.FloatField()),
                ('wind_speed_max', models.FloatField()),
            ],
        ),
    ]
