# Generated by Django 3.0.5 on 2020-05-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captureData', '0004_auto_20200504_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='pub_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
