# Generated by Django 3.0.5 on 2020-05-04 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captureData', '0005_auto_20200504_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='pub_date',
        ),
    ]
